# Generated by Django 4.0.3 on 2022-07-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_report', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'monthly'), ('annual', 'Annual'), ('onetime', 'One Time')], default='daily', max_length=9)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('date_period', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
