# Generated by Django 4.0.3 on 2022-03-17 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='', height_field=20, null=True, upload_to=None, verbose_name='image', width_field=20)),
                ('personal_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')])),
                ('father_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')])),
                ('sexuality', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$')])),
                ('maritalـstatus', models.CharField(choices=[('M', 'Maried'), ('S', 'Single')], default='S', max_length=1)),
                ('degreeـofـeducation', models.CharField(choices=[('D', 'Diploma'), ('B', 'Bachelor'), ('M', 'Master'), ('O', 'Other')], default='O', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profile.employee')),
            ],
            bases=('Profile.employee', models.Model),
        ),
    ]
