# Generated by Django 4.0.3 on 2022-04-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
