# Generated by Django 4.0.3 on 2022-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAndDateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.DateTimeField(blank=True, null=True)),
                ('end_point', models.DateTimeField(blank=True, null=True)),
                ('difference', models.DateTimeField(blank=True, null=True)),
                ('delay', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
