# Generated by Django 4.0.3 on 2022-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0003_alter_timeanddatetracker_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeanddatetracker',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeanddatetracker',
            name='end_point',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeanddatetracker',
            name='start_point',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
