# Generated by Django 4.0.3 on 2022-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0008_alter_timeanddatetracker_wasted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeanddatetracker',
            name='wasted_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
