# Generated by Django 4.0.3 on 2022-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0009_alter_timeanddatetracker_wasted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeanddatetracker',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='timeanddatetracker',
            name='start_point',
        ),
        migrations.AddField(
            model_name='timeanddatetracker',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
