# Generated by Django 4.0.3 on 2022-04-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0010_remove_timeanddatetracker_end_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeanddatetracker',
            name='duration',
        ),
        migrations.AddField(
            model_name='timeanddatetracker',
            name='end_point',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeanddatetracker',
            name='start_point',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
