# Generated by Django 4.0.3 on 2022-06-13 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0011_remove_timeanddatetracker_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeanddatetracker',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
