# Generated by Django 4.0.3 on 2022-06-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0012_timeanddatetracker_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeanddatetracker',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='timeanddatetracker',
            name='date',
        ),
    ]
