# Generated by Django 4.0.3 on 2022-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndDateTracker', '0013_rename_created_time_timeanddatetracker_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeanddatetracker',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
