# Generated by Django 4.0.3 on 2022-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
