# Generated by Django 4.0.3 on 2022-04-11 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degreeـofـeducation',
            field=models.CharField(choices=[('D', 'Diploma'), ('B', 'Bachelor'), ('M', 'Master'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalـstatus',
            field=models.CharField(choices=[('M', 'Maried'), ('S', 'Single')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='user',
            name='sexuality',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$')]),
        ),
    ]
