# Generated by Django 4.0.3 on 2022-04-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_user_address_user_birthdate_user_degreeـofـeducation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Register.company'),
        ),
    ]
