# Generated by Django 4.0.3 on 2022-05-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_user_check_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check_transportation',
        ),
    ]
