# Generated by Django 4.0.3 on 2022-07-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_remove_dormitory_capacity'),
        ('Register', '0009_alter_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_room', to='dormitory.dormitory'),
        ),
    ]
