# Generated by Django 4.0.3 on 2022-05-26 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='09(0[1-2]|1[0-9]|3[0-9]|2[0-1])-?[0-9]{3}-?[0-9]{4}')], verbose_name='phone number'),
        ),
    ]
