# Generated by Django 4.0.3 on 2022-07-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0010_user_room'),
        ('Register', '0013_alter_user_username'),
    ]

    operations = [
    ]
