# Generated by Django 4.0.3 on 2022-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0014_merge_0010_user_room_0013_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_transportation',
            field=models.BooleanField(default=False),
        ),
    ]
