# Generated by Django 4.0.3 on 2022-07-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0017_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degreeـofـeducation',
            new_name='degree_of_education',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='maritalـstatus',
            new_name='marital_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
    ]
