# Generated by Django 4.0.3 on 2022-07-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0017_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
    ]
