# Generated by Django 4.0.3 on 2022-06-29 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_form', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Declined'), ('A', 'Accepted')], default='P', max_length=1)),
                ('type_form', models.CharField(max_length=150)),
                ('value_form', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
