# Generated by Django 4.0.3 on 2022-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCounter', '0002_requestform_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
