# Generated by Django 4.0.3 on 2022-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCounter', '0003_alter_requestform_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
