# Generated by Django 4.0.3 on 2022-05-16 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServiceCounter', '0003_remove_responseapi_admin_admintransportation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransportation',
            name='user',
            field=models.ManyToManyField(related_name='admintranslates', to=settings.AUTH_USER_MODEL),
        ),
    ]
