# Generated by Django 4.0.3 on 2022-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransportation',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
