# Generated by Django 4.0.3 on 2022-05-03 14:31

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0002_admintransportation_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintransportation',
            old_name='city',
            new_name='address_search',
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
