# Generated by Django 4.0.3 on 2022-05-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transportation', '0005_alter_admintransportation_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransportation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
