# Generated by Django 4.0.3 on 2022-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0006_alter_admintransportation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransportation',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admintransportation',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admintransportation',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
