# Generated by Django 4.0.3 on 2022-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
