# Generated by Django 4.0.3 on 2022-05-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_hours', models.DecimalField(decimal_places=0, max_digits=9)),
                ('price_food', models.DecimalField(decimal_places=0, max_digits=9)),
                ('price_transportatio', models.DecimalField(decimal_places=0, max_digits=9)),
                ('price_dormitory', models.DecimalField(decimal_places=0, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
