# Generated by Django 4.0.3 on 2022-05-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='user',
            new_name='employee',
        ),
    ]
