# Generated by Django 4.0.3 on 2022-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_rename_user_employeesalary_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='price_dormitory',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='price_food',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='price_transportatio',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='salary_hours',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='min_working',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='reward_benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
