# Generated by Django 4.0.3 on 2022-06-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='builing_name',
            new_name='building_name',
        ),
    ]
