<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-25 15:46
=======
# Generated by Django 4.0.3 on 2022-06-30 12:04
>>>>>>> dormitory

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
