# Generated by Django 4.0.3 on 2022-05-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='company',
        ),
    ]
