# Generated by Django 4.0.3 on 2022-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_user_check_transportation'),
        ('Food', '0002_remove_food_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='company',
            field=models.ManyToManyField(blank=True, to='Register.company'),
        ),
    ]
