# Generated by Django 4.0.3 on 2022-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_remove_food_company_remove_food_user_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
