# Generated by Django 4.0.3 on 2022-05-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_food_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='company',
        ),
    ]
