# Generated by Django 4.0.3 on 2022-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_food_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='admin',
        ),
        migrations.AddField(
            model_name='food',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
