# Generated by Django 4.0.3 on 2022-05-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notepad', '0002_remove_note_file_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notepad.note'),
        ),
    ]
