# Generated by Django 4.0.3 on 2022-05-25 22:38

import Notepad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notepad', '0005_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Notepad.models.get_upload_path),
        ),
    ]
